# Generated by Django 5.0.1 on 2024-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(default='Vanilla', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank='True', null='True', upload_to='uploads/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank='True', null='True', upload_to='uploads/products'),
        ),
    ]
